# Test config file for Blip
module:
  module_name:  'blipnet_v1'
  module_type:  ['ml']
  module_mode:  ['training']
  gpu:          True
  gpu_device:   0
  verbose:      False

dataset:
  dataset_folder: "/home/ncarrara/physics/neutron/"
  dataset_files:  []
  dataset_type:   ''
  normalized:     true
  # ---- variables ----
  # Here we specify the location of the GUT variables in the files
  # and the weak values associated to the trial points.
  positions: []
  features: []
  classes: []
  labels: []
  # ---- normalization ----
  # Normalization parameters for positions and features.  Typically we want to normalize
  # input features depending on the type of task, or to unbias certain simulation parameters,
  # e.g. by normalizaing ADC over an event sample we remove the overall scale of the detector
  # response.
  position_normalization:   []
  features_normalization:   []

loader:
  loader_type:      ""
  batch_size:       518
  test_split:       0.1
  test_seed:        0
  validation_split: 0.3
  validation_seed:  0
  num_workers:      4

training:
  iterations:   1
  epochs:       10
  checkpoint:   10
  grad_norm:    true
  progress_bar: "all"        # train, validation, test, all
  rewrite_bar:      False # wether to leave bars after each epoch
  save_predictions: False  # wether to save network outputs in original file
  no_timing:    False     # wether to keep timing/memory info in callback
  skip_metrics: True
  seed:         0

model:
  # uncomment the line below and specify the model to load from a checkpoint.
  # load_model:   ".checkpoints/checkpoint_200.ckpt"
  BlipNet:
    dbscan_eps: 0.3
    dbscan_min: 10

criterion:
  BlipNetLoss:
    alpha: 1

metrics:

callbacks:

optimizer:
  optimizer_type: "Adam"
  learning_rate:  0.01
  betas:          [0.9, 0.999]
  epsilon:        1e-08
  weight_decay:   0.001
  momentum:       0.9